config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :posts

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :detail_types

  resources :engines

  resources :transmissions

  resources :bodies

  resources :makes

  resources :cities

  resources :orders do
    resources :comments
  end

  get 'my-orders/:email', to: 'orders#my', as: :my_orders, constraints: { email: /[^\/]+/ }

  get 'my-orders', to: 'orders#my_search', as: :my_orders_search_form

  get 'add_email_subscription_month', to: 'email_subscriptions#add_email_subscription_month', as: :add_email_subscription_month
  get 'email_subscription_status', to: 'email_subscriptions#email_subscription_status', as: :email_subscription_status

  post 'my-orders', to: 'orders#my', as: :my_orders_search, constraints: { email: /[^\/]+/ }

  post 'orders-filter', to: 'orders#filter', as: :orders_filter_form

  get 'orders-filter', to: 'orders#filter', as: :orders_filter

  get 'orders-unanswered', to: 'orders#unanswered', as: :orders_unanswered

  get 'welcome/index'

  get 'welcome/dealers'

  get 'welcome/add_funds'

  root 'welcome#index'

  devise_for :users, controllers: { registrations: 'registrations' }

end

app/models/engine.rb
# == Schema Information
#
# Table name: engines
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Engine < ActiveRecord::Base
  has_many :orders
end

app/controllers/engines_controller.rb
class EnginesController < ApplicationController
  before_action :deny_access
  before_action :set_engine, only: [:show, :edit, :update, :destroy]

  # GET /engines
  # GET /engines.json
  def index
    @engines = Engine.all
  end

  # GET /engines/1
  # GET /engines/1.json
  def show
  end

  # GET /engines/new
  def new
    @engine = Engine.new
  end

  # GET /engines/1/edit
  def edit
  end

  # POST /engines
  # POST /engines.json
  def create
    @engine = Engine.new(engine_params)

    respond_to do |format|
      if @engine.save
        format.html { redirect_to @engine, notice: 'Engine was successfully created.' }
        format.json { render :show, status: :created, location: @engine }
      else
        format.html { render :new }
        format.json { render json: @engine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /engines/1
  # PATCH/PUT /engines/1.json
  def update
    respond_to do |format|
      if @engine.update(engine_params)
        format.html { redirect_to @engine, notice: 'Engine was successfully updated.' }
        format.json { render :show, status: :ok, location: @engine }
      else
        format.html { render :edit }
        format.json { render json: @engine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /engines/1
  # DELETE /engines/1.json
  def destroy
    @engine.destroy
    respond_to do |format|
      format.html { redirect_to engines_url, notice: 'Engine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_engine
    @engine = Engine.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def engine_params
    params.require(:engine).permit(:name)
  end
end

app/helpers/engines_helper.rb
module EnginesHelper
end

app/views/engines/_form.html.erb
<%= form_for(@engine) do |f| %>
  <% if @engine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@engine.errors.count, "error") %> prohibited this engine from being saved:</h2>

      <ul>
      <% @engine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/engines/edit.html.erb
<h1>Editing Engine</h1>

<%= render 'form' %>

<%= link_to 'Show', @engine %> |
<%= link_to 'Back', engines_path %>

app/views/engines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Engines</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @engines.each do |engine| %>
      <tr>
        <td><%= engine.name %></td>
        <td><%= link_to 'Show', engine %></td>
        <td><%= link_to 'Edit', edit_engine_path(engine) %></td>
        <td><%= link_to 'Destroy', engine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Engine', new_engine_path %>

app/views/engines/new.html.erb
<h1>New Engine</h1>

<%= render 'form' %>

<%= link_to 'Back', engines_path %>

app/views/engines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @engine.name %>
</p>

<%= link_to 'Edit', edit_engine_path(@engine) %> |
<%= link_to 'Back', engines_path %>