config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :posts

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :detail_types

  resources :engines

  resources :transmissions

  resources :bodies

  resources :makes

  resources :cities

  resources :orders do
    resources :comments
  end

  get 'my-orders/:email', to: 'orders#my', as: :my_orders, constraints: { email: /[^\/]+/ }

  get 'my-orders', to: 'orders#my_search', as: :my_orders_search_form

  get 'add_email_subscription_month', to: 'email_subscriptions#add_email_subscription_month', as: :add_email_subscription_month
  get 'email_subscription_status', to: 'email_subscriptions#email_subscription_status', as: :email_subscription_status

  post 'my-orders', to: 'orders#my', as: :my_orders_search, constraints: { email: /[^\/]+/ }

  post 'orders-filter', to: 'orders#filter', as: :orders_filter_form

  get 'orders-filter', to: 'orders#filter', as: :orders_filter

  get 'orders-unanswered', to: 'orders#unanswered', as: :orders_unanswered

  get 'welcome/index'

  get 'welcome/dealers'

  get 'welcome/add_funds'

  root 'welcome#index'

  devise_for :users, controllers: { registrations: 'registrations' }

end

app/models/body.rb
# == Schema Information
#
# Table name: bodies
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Body < ActiveRecord::Base
  has_many :orders
end

app/controllers/bodies_controller.rb
class BodiesController < ApplicationController
  before_action :deny_access
  before_action :set_body, only: [:show, :edit, :update, :destroy]

  # GET /bodies
  # GET /bodies.json
  def index
    @bodies = Body.all
  end

  # GET /bodies/1
  # GET /bodies/1.json
  def show
  end

  # GET /bodies/new
  def new
    @body = Body.new
  end

  # GET /bodies/1/edit
  def edit
  end

  # POST /bodies
  # POST /bodies.json
  def create
    @body = Body.new(body_params)

    respond_to do |format|
      if @body.save
        format.html { redirect_to @body, notice: 'Body was successfully created.' }
        format.json { render :show, status: :created, location: @body }
      else
        format.html { render :new }
        format.json { render json: @body.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bodies/1
  # PATCH/PUT /bodies/1.json
  def update
    respond_to do |format|
      if @body.update(body_params)
        format.html { redirect_to @body, notice: 'Body was successfully updated.' }
        format.json { render :show, status: :ok, location: @body }
      else
        format.html { render :edit }
        format.json { render json: @body.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bodies/1
  # DELETE /bodies/1.json
  def destroy
    @body.destroy
    respond_to do |format|
      format.html { redirect_to bodies_url, notice: 'Body was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_body
    @body = Body.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def body_params
    params.require(:body).permit(:name)
  end
end

app/helpers/bodies_helper.rb
module BodiesHelper
end

app/views/bodies/_form.html.erb
<%= form_for(@body) do |f| %>
  <% if @body.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@body.errors.count, "error") %> prohibited this body from being saved:</h2>

      <ul>
      <% @body.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bodies/edit.html.erb
<h1>Editing Body</h1>

<%= render 'form' %>

<%= link_to 'Show', @body %> |
<%= link_to 'Back', bodies_path %>

app/views/bodies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bodies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bodies.each do |body| %>
      <tr>
        <td><%= body.name %></td>
        <td><%= link_to 'Show', body %></td>
        <td><%= link_to 'Edit', edit_body_path(body) %></td>
        <td><%= link_to 'Destroy', body, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Body', new_body_path %>

app/views/bodies/new.html.erb
<h1>New Body</h1>

<%= render 'form' %>

<%= link_to 'Back', bodies_path %>

app/views/bodies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @body.name %>
</p>

<%= link_to 'Edit', edit_body_path(@body) %> |
<%= link_to 'Back', bodies_path %>