config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :posts

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :detail_types

  resources :engines

  resources :transmissions

  resources :bodies

  resources :makes

  resources :cities

  resources :orders do
    resources :comments
  end

  get 'my-orders/:email', to: 'orders#my', as: :my_orders, constraints: { email: /[^\/]+/ }

  get 'my-orders', to: 'orders#my_search', as: :my_orders_search_form

  get 'add_email_subscription_month', to: 'email_subscriptions#add_email_subscription_month', as: :add_email_subscription_month
  get 'email_subscription_status', to: 'email_subscriptions#email_subscription_status', as: :email_subscription_status

  post 'my-orders', to: 'orders#my', as: :my_orders_search, constraints: { email: /[^\/]+/ }

  post 'orders-filter', to: 'orders#filter', as: :orders_filter_form

  get 'orders-filter', to: 'orders#filter', as: :orders_filter

  get 'orders-unanswered', to: 'orders#unanswered', as: :orders_unanswered

  get 'welcome/index'

  get 'welcome/dealers'

  get 'welcome/add_funds'

  root 'welcome#index'

  devise_for :users, controllers: { registrations: 'registrations' }

end

app/controllers/detail_types_controller.rb
class DetailTypesController < ApplicationController
  before_action :deny_access
  before_action :set_detail_type, only: [:show, :edit, :update, :destroy]

  # GET /detail_types
  # GET /detail_types.json
  def index
    @detail_types = DetailType.all
  end

  # GET /detail_types/1
  # GET /detail_types/1.json
  def show
  end

  # GET /detail_types/new
  def new
    @detail_type = DetailType.new
  end

  # GET /detail_types/1/edit
  def edit
  end

  # POST /detail_types
  # POST /detail_types.json
  def create
    @detail_type = DetailType.new(detail_type_params)

    respond_to do |format|
      if @detail_type.save
        format.html { redirect_to @detail_type, notice: 'Detail type was successfully created.' }
        format.json { render :show, status: :created, location: @detail_type }
      else
        format.html { render :new }
        format.json { render json: @detail_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /detail_types/1
  # PATCH/PUT /detail_types/1.json
  def update
    respond_to do |format|
      if @detail_type.update(detail_type_params)
        format.html { redirect_to @detail_type, notice: 'Detail type was successfully updated.' }
        format.json { render :show, status: :ok, location: @detail_type }
      else
        format.html { render :edit }
        format.json { render json: @detail_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /detail_types/1
  # DELETE /detail_types/1.json
  def destroy
    @detail_type.destroy
    respond_to do |format|
      format.html { redirect_to detail_types_url, notice: 'Detail type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_detail_type
    @detail_type = DetailType.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def detail_type_params
    params.require(:detail_type).permit(:name)
  end
end

app/helpers/detail_types_helper.rb
module DetailTypesHelper
end

app/views/detail_types/_form.html.erb
<%= form_for(@detail_type) do |f| %>
  <% if @detail_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@detail_type.errors.count, "error") %> prohibited this detail_type from being saved:</h2>

      <ul>
      <% @detail_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/detail_types/edit.html.erb
<h1>Editing Detail Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @detail_type %> |
<%= link_to 'Back', detail_types_path %>

app/views/detail_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Detail Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @detail_types.each do |detail_type| %>
      <tr>
        <td><%= detail_type.name %></td>
        <td><%= link_to 'Show', detail_type %></td>
        <td><%= link_to 'Edit', edit_detail_type_path(detail_type) %></td>
        <td><%= link_to 'Destroy', detail_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Detail type', new_detail_type_path %>

app/views/detail_types/new.html.erb
<h1>New Detail Type</h1>

<%= render 'form' %>

<%= link_to 'Back', detail_types_path %>

app/views/detail_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @detail_type.name %>
</p>

<%= link_to 'Edit', edit_detail_type_path(@detail_type) %> |
<%= link_to 'Back', detail_types_path %>