config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :posts

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :detail_types

  resources :engines

  resources :transmissions

  resources :bodies

  resources :makes

  resources :cities

  resources :orders do
    resources :comments
  end

  get 'my-orders/:email', to: 'orders#my', as: :my_orders, constraints: { email: /[^\/]+/ }

  get 'my-orders', to: 'orders#my_search', as: :my_orders_search_form

  get 'add_email_subscription_month', to: 'email_subscriptions#add_email_subscription_month', as: :add_email_subscription_month
  get 'email_subscription_status', to: 'email_subscriptions#email_subscription_status', as: :email_subscription_status

  post 'my-orders', to: 'orders#my', as: :my_orders_search, constraints: { email: /[^\/]+/ }

  post 'orders-filter', to: 'orders#filter', as: :orders_filter_form

  get 'orders-filter', to: 'orders#filter', as: :orders_filter

  get 'orders-unanswered', to: 'orders#unanswered', as: :orders_unanswered

  get 'welcome/index'

  get 'welcome/dealers'

  get 'welcome/add_funds'

  root 'welcome#index'

  devise_for :users, controllers: { registrations: 'registrations' }

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta property="og:type" content="website">
  <meta property="og:url" content="http://zappo.by">
  <meta property="og:title" content="Подбор автозапчастей zappo.by">
  <meta property="og:image" content="https://pp.vk.me/c623326/v623326002/3ab67/uz572p0wTQM.jpg">
  <meta property="og:description" content="Вы создаете заказ на запчасть, он рассылается в более, чем сотню магазинов. Далее они высылают вам предложения и вы выбираете самое лучшее и выгодное! За репост большая благодарность!">
  <title><%= content_for?(:title) ? yield(:title) : "ZAPPO.BY - Подбор автозапчастей" %></title>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag "application" %>
  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

</head>
<body>

<div class="navigation-bar navbar-fixed-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/"><%= $APPLICATION_NAME %></a>

    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Мои заказы", my_orders_search_form_path %></li>
        <% if user_signed_in? %>
            <li><%= link_to "Все заказы", orders_path, class: 'btn-success animated fadeIn' %></li>
            <li><%= link_to "Без ответов", orders_unanswered_path, class: 'btn-warning animated fadeIn' %></li>
        <% end %>
        <li><%= link_to "Для продавцов", welcome_dealers_path %></li>
      </ul>

      <div class="navbar-right">
        <%= render :partial => 'welcome/user_info' %>
      </div>
    </div>

  </div>
</div>
<% if user_signed_in? %>
    <div class="top-buffer-4"></div>
<% end %>
<div class="top-buffer-2"></div>

<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <% if user_signed_in? %>
      <div class="row">
        <div class="top-buffer-2"></div>
        <div class="col-lg-12 text-right">
          <a href="http://zappo.by/orders/123/comments/new#new_comment"><i class="fa fa-bug"></i> Сообщить об ошибке / <i class="fa fa-lightbulb-o"></i> Предложить идею</a>
        </div>
      </div>
      <% end %>
      <%= bootstrap_flash %>
      <%= yield %>
    </div>
  </div>
  <!--/row-->

</div>
<!-- /container -->

<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-6">
        <p>&copy; <%= $APPLICATION_NAME %> 2015</p>
        <p class="text-muted">Контакты:</p>
        <p>
          <p class="text-muted">+375447165233 Дмитрий</p>
          <p class="text-muted">+375291631849 Диана</p>
          <p class="text-muted">+375292791526 Валентин</p>
        </p>
      </div>
      <div class="col-lg-6">
        <p class="animated text-success infinite pulse">Мы будем очень благодарны, если вы поделитесь в социальных сетях:</p>
        <div class="social-likes" data-url="http://zappo.by" data-title="Подбор автозапчастей">
          <div class="facebook" title="Поделиться ссылкой на Фейсбуке">Facebook</div>
          <div class="twitter" title="Поделиться ссылкой в Твиттере">Twitter</div>
          <div class="mailru" title="Поделиться ссылкой в Моём мире">Мой мир</div>
          <div class="vkontakte" title="Поделиться ссылкой во Вконтакте">Вконтакте</div>
          <div class="odnoklassniki" title="Поделиться ссылкой в Одноклассниках">Одноклассники</div>
          <div class="plusone" title="Поделиться ссылкой в Гугл-плюсе">Google+</div>
        </div>
      </div>
    </div>
    <!--/row-->
  </div>
  <!-- /container -->
</footer>

<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-40228685-4', 'auto');
    ga('send', 'pageview');

</script>

<!-- Yandex.Metrika counter -->
<script type="text/javascript">
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter31561323 = new Ya.Metrika({
                    id:31561323,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true,
                    webvisor:true,
                    trackHash:true
                });
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
                s = d.createElement("script"),
                f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = "https://mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/31561323" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

<%= stylesheet_link_tag "application", :media => "all" %>

</body>
</html>